version: 2.1
orbs:
  node: circleci/node@7.2.1
jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:20.0
    executor: node/default
    steps:      
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "test"
          command: npm run test
  integrationFrontend:
    docker:
      - image: cimg/node:20.0
    steps:
      - run:
          name: "Cloneage des dépôts backend puis frontend"
          command: |
            git clone https://github.com/komazia/backend_labo1.git
            git clone https://github.com/komazia/frontend_labo1.git      
      - run:
          name: "Installation de dépendences du frontend"
          command: |
            cd frontend_labo1
            npm install
            npm run build
      - run:
          name: "Intégration du build dans le backend"
          command: |
            mkdir -p backend_labo1/public
            cp -rT frontend_labo1/build/. backend_labo1/public/
      - persist_to_workspace:
          root: .
          paths:
            - backend_labo1           
  deploiement:
    docker:
      - image: cimg/node:20.0
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: "Vérification des fichiers"
          command: |
            cd backend_labo1
            ls -Rl
workflows:
  labo1-workflow: 
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
